name: Extract Flutter Project

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract ZIP
        run: |
          ZIP=$(find . -maxdepth 1 -type f -iname "*.zip" | head -n 1)

          if [ -z "$ZIP" ]; then
            echo "ZIP não encontrado"
            exit 1
          fi

          mkdir extracted
          unzip -q "$ZIP" -d extracted

          PROJECT_ROOT=$(find extracted -type d -name android -print -quit | xargs dirname)

          if [ -z "$PROJECT_ROOT" ]; then
            echo "Pasta android não encontrada"
            exit 1
          fi

          cp -a "$PROJECT_ROOT"/. ./

          rm -rf extracted
          rm -f "$ZIP"

      - name: Verify
        run: |
          test -d android
          test -d lib
          test -f pubspec.yaml
          test -f codemagic.yaml
          echo "PROJETO OK!"

      - name: Save changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Extract Flutter project"
          git push
